package com.dummyspaces.temporaryproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class temp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public temp() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public temp(java.lang.String name) {
		this.name = name;
	}

}