package com.dummyspaces.temporaryproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class temp implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public temp() {
    }




}